{
    "swagger": "2.0",
    "info": {
        "title": "Messages server",
        "description": "SAFRSAPI",
        "termsOfService": "",
        "version": "0.0"
    },
    "host": "127.0.0.1:5000",
    "paths": {
        "/Messages/": {
            "get": {
                "tags": [
                    "Messages"
                ],
                "summary": "Retrieve a collection of Message objects",
                "parameters": [
                    {
                        "default": "",
                        "type": "string",
                        "name": "include",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Message relationships to include (csv)"
                    },
                    {
                        "default": "content,from_user_id,to_user_id",
                        "type": "string",
                        "name": "fields[Message]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Message fields to include (csv)"
                    },
                    {
                        "default": 0,
                        "type": "integer",
                        "name": "page[offset]",
                        "in": "query",
                        "format": "int64",
                        "required": false,
                        "description": "Page offset"
                    },
                    {
                        "default": 10,
                        "type": "integer",
                        "name": "page[limit]",
                        "in": "query",
                        "format": "int64",
                        "required": false,
                        "description": "Max number of items"
                    },
                    {
                        "default": "content,from_user_id,to_user_id,id",
                        "type": "string",
                        "name": "sort",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Sort order"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[content]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "content attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[from_user_id]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "from_user_id attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[to_user_id]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "to_user_id attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[id]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "id attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Custom Message filter"
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "type": "string",
                        "default": "application/vnd.api+json",
                        "enum": [
                            "application/vnd.api+json",
                            "application/json"
                        ],
                        "required": true
                    }
                ],
                "responses": {
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_403"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_404"
                        }
                    },
                    "200": {
                        "schema": {
                            "$ref": "#/definitions/Message_coll1"
                        },
                        "description": "Request fulfilled, document follows"
                    },
                    "405": {
                        "description": "Specified method is invalid for this resource",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_405"
                        }
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_500"
                        }
                    }
                },
                "produces": [
                    "application/vnd.api+json"
                ],
                "description": "Retrieve Message from Messages",
                "operationId": "RetrieveacollectionofMessageobjects_0"
            },
            "post": {
                "tags": [
                    "Messages"
                ],
                "summary": "Create Message",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "type": "string",
                        "default": "application/vnd.api+json",
                        "enum": [
                            "application/vnd.api+json",
                            "application/json"
                        ],
                        "required": true
                    },
                    {
                        "name": "POST body",
                        "in": "body",
                        "description": "Message attributes",
                        "schema": {
                            "$ref": "#/definitions/Message_inst1"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_403"
                        }
                    },
                    "202": {
                        "description": "Accepted"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_404"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_409"
                        }
                    },
                    "201": {
                        "schema": {
                            "$ref": "#/definitions/Message_inst1"
                        },
                        "description": "Created"
                    },
                    "405": {
                        "description": "Specified method is invalid for this resource",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_405"
                        }
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_500"
                        }
                    }
                },
                "produces": [
                    "application/vnd.api+json"
                ],
                "operationId": "CreateMessage_0"
            }
        },
        "/Messages/{MessageId}/": {
            "get": {
                "tags": [
                    "Messages"
                ],
                "summary": "Retrieve Message instance",
                "parameters": [
                    {
                        "default": "",
                        "type": "string",
                        "name": "include",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Message relationships to include (csv)"
                    },
                    {
                        "default": "content,from_user_id,to_user_id",
                        "type": "string",
                        "name": "fields[Message]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Message fields to include (csv)"
                    },
                    {
                        "name": "MessageId",
                        "in": "path",
                        "type": "string",
                        "default": "1232",
                        "required": true
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "type": "string",
                        "default": "application/vnd.api+json",
                        "enum": [
                            "application/vnd.api+json",
                            "application/json"
                        ],
                        "required": true
                    }
                ],
                "responses": {
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_403"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_404"
                        }
                    },
                    "200": {
                        "schema": {
                            "$ref": "#/definitions/Message_inst1"
                        },
                        "description": "Request fulfilled, document follows"
                    },
                    "405": {
                        "description": "Specified method is invalid for this resource",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_405"
                        }
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_500"
                        }
                    }
                },
                "produces": [
                    "application/vnd.api+json"
                ],
                "description": "Retrieve Message from Messages",
                "operationId": "RetrieveMessageinstance_0"
            },
            "delete": {
                "tags": [
                    "Messages"
                ],
                "parameters": [
                    {
                        "name": "MessageId",
                        "in": "path",
                        "type": "string",
                        "default": "1232",
                        "required": true
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "type": "string",
                        "default": "application/vnd.api+json",
                        "enum": [
                            "application/vnd.api+json",
                            "application/json"
                        ],
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "204": {
                        "description": "Request fulfilled, nothing follows"
                    },
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Message_inst1"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_403"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_404"
                        }
                    },
                    "405": {
                        "description": "Specified method is invalid for this resource",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_405"
                        }
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_500"
                        }
                    }
                },
                "produces": [
                    "application/vnd.api+json"
                ],
                "summary": "Delete Message from Messages",
                "operationId": "DeleteMessagefromMessages_0"
            }
        },
        "/Users/": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Retrieve a collection of User objects",
                "parameters": [
                    {
                        "default": "incoming_messages",
                        "type": "string",
                        "name": "include",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "User relationships to include (csv)"
                    },
                    {
                        "default": "name",
                        "type": "string",
                        "name": "fields[User]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "User fields to include (csv)"
                    },
                    {
                        "default": 0,
                        "type": "integer",
                        "name": "page[offset]",
                        "in": "query",
                        "format": "int64",
                        "required": false,
                        "description": "Page offset"
                    },
                    {
                        "default": 10,
                        "type": "integer",
                        "name": "page[limit]",
                        "in": "query",
                        "format": "int64",
                        "required": false,
                        "description": "Max number of items"
                    },
                    {
                        "default": "name,id",
                        "type": "string",
                        "name": "sort",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Sort order"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[name]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "name attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[id]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "id attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Custom User filter"
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "type": "string",
                        "default": "application/vnd.api+json",
                        "enum": [
                            "application/vnd.api+json",
                            "application/json"
                        ],
                        "required": true
                    }
                ],
                "responses": {
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_403"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_404"
                        }
                    },
                    "200": {
                        "schema": {
                            "$ref": "#/definitions/User_coll1"
                        },
                        "description": "Request fulfilled, document follows"
                    },
                    "405": {
                        "description": "Specified method is invalid for this resource",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_405"
                        }
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_500"
                        }
                    }
                },
                "produces": [
                    "application/vnd.api+json"
                ],
                "description": "Retrieve User from Users",
                "operationId": "RetrieveacollectionofUserobjects_0"
            },
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "type": "string",
                        "default": "application/vnd.api+json",
                        "enum": [
                            "application/vnd.api+json",
                            "application/json"
                        ],
                        "required": true
                    },
                    {
                        "name": "POST body",
                        "in": "body",
                        "description": "User attributes",
                        "schema": {
                            "$ref": "#/definitions/User_inst1"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_403"
                        }
                    },
                    "202": {
                        "description": "Accepted"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_404"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_409"
                        }
                    },
                    "201": {
                        "schema": {
                            "$ref": "#/definitions/User_inst1"
                        },
                        "description": "Created"
                    },
                    "405": {
                        "description": "Specified method is invalid for this resource",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_405"
                        }
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_500"
                        }
                    }
                },
                "produces": [
                    "application/vnd.api+json"
                ],
                "operationId": "CreateUser_0"
            }
        },
        "/Users/{UserId}/": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Retrieve User instance",
                "parameters": [
                    {
                        "default": "incoming_messages",
                        "type": "string",
                        "name": "include",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "User relationships to include (csv)"
                    },
                    {
                        "default": "name",
                        "type": "string",
                        "name": "fields[User]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "User fields to include (csv)"
                    },
                    {
                        "name": "UserId",
                        "in": "path",
                        "type": "string",
                        "default": "aa7aa833-dac6-40ba-8de7-28eb3b1dfc51",
                        "required": true
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "type": "string",
                        "default": "application/vnd.api+json",
                        "enum": [
                            "application/vnd.api+json",
                            "application/json"
                        ],
                        "required": true
                    }
                ],
                "responses": {
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_403"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_404"
                        }
                    },
                    "200": {
                        "schema": {
                            "$ref": "#/definitions/User_inst1"
                        },
                        "description": "Request fulfilled, document follows"
                    },
                    "405": {
                        "description": "Specified method is invalid for this resource",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_405"
                        }
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_500"
                        }
                    }
                },
                "produces": [
                    "application/vnd.api+json"
                ],
                "description": "Retrieve User from Users",
                "operationId": "RetrieveUserinstance_0"
            },
            "delete": {
                "tags": [
                    "Users"
                ],
                "parameters": [
                    {
                        "name": "UserId",
                        "in": "path",
                        "type": "string",
                        "default": "aa7aa833-dac6-40ba-8de7-28eb3b1dfc51",
                        "required": true
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "type": "string",
                        "default": "application/vnd.api+json",
                        "enum": [
                            "application/vnd.api+json",
                            "application/json"
                        ],
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "204": {
                        "description": "Request fulfilled, nothing follows"
                    },
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/User_inst1"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_403"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_404"
                        }
                    },
                    "405": {
                        "description": "Specified method is invalid for this resource",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_405"
                        }
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_500"
                        }
                    }
                },
                "produces": [
                    "application/vnd.api+json"
                ],
                "summary": "Delete User from Users",
                "operationId": "DeleteUserfromUsers_0"
            }
        },
        "/Users/{UserId}/incoming_messages": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Retrieve Message from incoming_messages",
                "description": "Retrieve Message items from the User incoming_messages \"to-many\" relationship",
                "parameters": [
                    {
                        "default": "",
                        "type": "string",
                        "name": "include",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Message relationships to include (csv)"
                    },
                    {
                        "default": "content,from_user_id,to_user_id",
                        "type": "string",
                        "name": "fields[Message]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Message fields to include (csv)"
                    },
                    {
                        "default": 0,
                        "type": "integer",
                        "name": "page[offset]",
                        "in": "query",
                        "format": "int64",
                        "required": false,
                        "description": "Page offset"
                    },
                    {
                        "default": 10,
                        "type": "integer",
                        "name": "page[limit]",
                        "in": "query",
                        "format": "int64",
                        "required": false,
                        "description": "Max number of items"
                    },
                    {
                        "default": "content,from_user_id,to_user_id,id",
                        "type": "string",
                        "name": "sort",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Sort order"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[content]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "content attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[from_user_id]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "from_user_id attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[to_user_id]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "to_user_id attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter[id]",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "id attribute filter (csv)"
                    },
                    {
                        "default": "",
                        "type": "string",
                        "name": "filter",
                        "in": "query",
                        "format": "string",
                        "required": false,
                        "description": "Custom Message filter"
                    },
                    {
                        "name": "UserId",
                        "in": "path",
                        "type": "string",
                        "default": "aa7aa833-dac6-40ba-8de7-28eb3b1dfc51",
                        "description": "User item",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request fulfilled, document follows",
                        "schema": {
                            "$ref": "#/definitions/User.incoming_messages_rel_coll"
                        }
                    },
                    "404": {
                        "description": "Nothing matches the given URI",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_404"
                        }
                    },
                    "405": {
                        "description": "Specified method is invalid for this resource",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_405"
                        }
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/jsonapi_error_500"
                        }
                    }
                },
                "operationId": "RetrieveMessagefromincomingmessages_0"
            }
        }
    },
    "definitions": {
        "jsonapi_error_403": {
            "properties": {
                "errors": {
                    "example": [
                        {
                            "title": "Request forbidden -- authorization will not help",
                            "detail": "",
                            "code": "403"
                        }
                    ],
                    "type": "string"
                }
            },
            "description": ""
        },
        "jsonapi_error_404": {
            "properties": {
                "errors": {
                    "example": [
                        {
                            "title": "Nothing matches the given URI",
                            "detail": "",
                            "code": "404"
                        }
                    ],
                    "type": "string"
                }
            },
            "description": ""
        },
        "User_coll1": {
            "properties": {
                "data": {
                    "example": [
                        {
                            "attributes": {
                                "name": ""
                            },
                            "type": "User",
                            "id": "aa7aa833-dac6-40ba-8de7-28eb3b1dfc51",
                            "relationships": {
                                "incoming_messages": {
                                    "data": [],
                                    "links": {
                                        "self": null
                                    }
                                }
                            }
                        }
                    ],
                    "type": "string"
                }
            },
            "description": "User get;"
        },
        "jsonapi_error_405": {
            "properties": {
                "errors": {
                    "example": [
                        {
                            "title": "Specified method is invalid for this resource",
                            "detail": "",
                            "code": "405"
                        }
                    ],
                    "type": "string"
                }
            },
            "description": ""
        },
        "jsonapi_error_400": {
            "properties": {
                "errors": {
                    "example": [
                        {
                            "title": "Bad request syntax or unsupported method",
                            "detail": "",
                            "code": "400"
                        }
                    ],
                    "type": "string"
                }
            },
            "description": ""
        },
        "jsonapi_error_500": {
            "properties": {
                "errors": {
                    "example": [
                        {
                            "title": "Server got itself in trouble",
                            "detail": "",
                            "code": "500"
                        }
                    ],
                    "type": "string"
                }
            },
            "description": ""
        },
        "User_inst1": {
            "properties": {
                "data": {
                    "example": {
                        "attributes": {
                            "name": ""
                        },
                        "type": "User"
                    },
                    "type": "string"
                }
            },
            "description": "User post;"
        },
        "jsonapi_error_409": {
            "properties": {
                "errors": {
                    "example": [
                        {
                            "title": "Request conflict",
                            "detail": "",
                            "code": "409"
                        }
                    ],
                    "type": "string"
                }
            },
            "description": ""
        },
        "User_inst": {
            "properties": {
                "data": {
                    "example": {
                        "attributes": {
                            "name": ""
                        },
                        "type": "User",
                        "id": "aa7aa833-dac6-40ba-8de7-28eb3b1dfc51"
                    },
                    "type": "string"
                }
            },
            "description": "User patch;User post;User delete;User patch;User post;User delete;"
        },
        "User.incoming_messages_rel_coll": {
            "properties": {
                "data": {
                    "example": [
                        {
                            "type": "Message",
                            "id": "1232"
                        }
                    ],
                    "type": "string"
                }
            },
            "description": "User.incoming_messages patch relationship;User.incoming_messages post relationship;"
        },
        "User_coll": {
            "properties": {
                "data": {
                    "example": [
                        {
                            "attributes": {
                                "name": ""
                            },
                            "type": "User",
                            "id": "aa7aa833-dac6-40ba-8de7-28eb3b1dfc51"
                        }
                    ],
                    "type": "string"
                }
            }
        },
        "Message_coll1": {
            "properties": {
                "data": {
                    "example": [
                        {
                            "attributes": {
                                "content": "",
                                "from_user_id": "",
                                "to_user_id": ""
                            },
                            "type": "Message",
                            "id": "1232",
                            "relationships": {}
                        }
                    ],
                    "type": "string"
                }
            },
            "description": "Message get;"
        },
        "Message_inst1": {
            "properties": {
                "data": {
                    "example": {
                        "attributes": {
                            "content": "",
                            "from_user_id": "",
                            "to_user_id": ""
                        },
                        "type": "Message"
                    },
                    "type": "string"
                }
            },
            "description": "Message post;"
        },
        "Message_inst": {
            "properties": {
                "data": {
                    "example": {
                        "attributes": {
                            "content": "",
                            "from_user_id": "",
                            "to_user_id": ""
                        },
                        "type": "Message",
                        "id": "1232"
                    },
                    "type": "string"
                }
            },
            "description": "Message patch;Message post;Message delete;Message patch;Message post;Message delete;"
        },
        "Message_coll": {
            "properties": {
                "data": {
                    "example": [
                        {
                            "attributes": {
                                "content": "",
                                "from_user_id": "",
                                "to_user_id": ""
                            },
                            "type": "Message",
                            "id": "1232"
                        }
                    ],
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "User description",
            "name": "Users"
        },
        {
            "description": "User description",
            "name": "Messages"
        }
    ]
}
